apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: px-csi-snapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: pxd.portworx.com
deletionPolicy: Delete
parameters:
  csi.storage.k8s.io/snapshotter-secret-name: px-user-token
  csi.storage.k8s.io/snapshotter-secret-namespace: portworx
