kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: px-csi-db-enc-sharedv4
provisioner: pxd.portworx.com
parameters:
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: px-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
  repl: '2'
  io_profile: db_remote
  disable_io_profile_protection: '1'
  secure: 'true'
  csi.storage.k8s.io/node-publish-secret-name: px-secret
  io_priority: high
  cow_ondemand: 'false'
  sharedv4: "true"
  sharedv4_svc_type: "ClusterIP"
allowVolumeExpansion: true
volumeBindingMode: Immediate