kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: px-sharedv4-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  sharedv4: "true"
  sharedv4_svc_type: "ClusterIP"
  repl: "2"
  io_profile: "db_remote"
  io_priority: "high"
  secure: "true"
  cow_ondemand: "false"
  disable_io_profile_protection: "1"
