apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-snap-clone
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: postgres-group-cloudsnapshot-data-postgres-sts-0-43c2ba39-9061-4937-a545-f66f48ecabf1 
spec:
  accessModes:
     - ReadWriteOnce
  storageClassName: stork-snapshot-sc
  resources:
    requests:
      storage: 5Gi
